#
##adding a default active profile that will run when we start the application
#spring:
#  profiles:
#    active :
#      dev
#
#
#---   # Creating document with " --- "
#
#spring:
#  profiles: dev
#
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: ''
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#
#  # Allowing all the endpoints for the Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#---
#
#spring:
#  profiles: qa
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: ''
#    url: jdbc:mysql://localhost:3306/departmentsringrestfuldb-QA   # You have to add a different DB for every profile
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
#---
#
#spring:
#  profiles: prod
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: ''
#    url: jdbc:mysql://localhost:3306/departmentsringrestfuldb-PROD   # You have to add a different DB for every profile
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
